default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 8
  host: localhost

development:
  <<: *default
  database: colchonet_dev

test:
  <<: *default
  database: colchonet_test

production:
  <<: *default
  database: colchonet_prod
